Remove the lint about non nullable binding instances
creativecreatorormaybenot/performance pull request #19
Opened 2022-07-25 13:36 UTC by ValentinVignal

Fixes https://github.com/creativecreatorormaybenot/performance/issues/18

I used the fix recommended by the flutter team: https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0#your-code

I also run `flutter pub get`, tell me if you want me to remove those changes

2022-07-26 21:12 UTC, creativecreatorormaybenot requested changes
[`SchedulerBinding.instance`](https://api.flutter.dev/flutter/scheduler/SchedulerBinding/instance.html) is no longer nullable on stable, which means that the `_ambiguate` function is unnecessary.

2022-07-27 00:45 UTC, ValentinVignal commented
I can not use `_ambiguate` if you want but it will be a breaking change. A project that didn't upgrade to flutter 3 won't be able to use the new version of this package. Is that fine ?

2022-07-27 11:36 UTC, creativecreatorormaybenot commented
@ValentinVignal It is not a breaking change since we expect everyone using the package to be on the stable channel of Flutter (this is also what the Pub analysis tool uses).

2022-07-27 13:32 UTC, ValentinVignal commented
@creativecreatorormaybenot fair enough, I removed `_ambiguate` in https://github.com/creativecreatorormaybenot/performance/pull/19/commits/c57bbd97379bad6cfdc93c8a92a030e766c89a5b

2022-07-28 09:23 UTC, creativecreatorormaybenot approved these changes
lgtm

Two additional things I would change:
1. Could you bump the version and add an entry to the CHANGELOG.md file? That would be version `0.1.1`.
2. I realize this is my mistake, but the `performance/pubspec.lock` should not be committed (only the lock file of the example app). Could you delete that and add it to `performance/.gitignore`?

Let me know if you want to do that as part of this PR. Otherwise, I will just create a follow-up PR.

2022-07-28 10:21 UTC, ValentinVignal commented
@creativecreatorormaybenot That is fine, I can do it in this PR. I pushed the changes, tell me if something else needs to be changed.

2022-07-28 17:29 UTC, creativecreatorormaybenot approved these changes
LGTM

2022-07-28 17:29 UTC, creativecreatorormaybenot commented on performance/CHANGELOG.md
> +* Migrate the code to Flutter 3 by considering `SchedulerBinding.instance` non-nullable.
```suggestion
* Fixed warnings introduced by Flutter 3 (`SchedulerBinding.instance` is now non-nullable).
```

2022-07-28 17:29 UTC, creativecreatorormaybenot commented on performance/pubspec.yaml
> +  flutter: ">=1.17.0"
```suggestion
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=1.17.0'
```

2022-07-28 17:30 UTC, creativecreatorormaybenot commented
@ValentinVignal Thank you so much for your contribution!

2022-08-08 07:59 UTC, ValentinVignal commented
@creativecreatorormaybenot Is there something else I need to do for it to be merged and released?

2022-08-08 11:09 UTC, creativecreatorormaybenot commented
@ValentinVignal your commits were not signed. But I removed this requirement now as I am going to squash anyway (in which case GitHub will sign the squash commit).

2022-08-08 11:11 UTC, merged